(function(){
function esc(x){ return (typeof h==='function') ? h(x) : String(x??'').replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
function listHtml(arr){ return (arr||[]).map(x=>`<li>${esc(x)}</li>`).join(''); }
function tagsHtml(arr){ return (arr||[]).map(t=>`<span class="resource-tag ${esc(t.kind||'')}">${esc(t.text||t)}</span>`).join(''); }
function renderStdAnswer(ans){ if(!ans) return ''; return `<div class="answer-box"><h6>标准解答与结论</h6>${ans.overview?`<div class="answer-overview">${esc(ans.overview)}</div>`:''}${ans.known?`<div class="answer-overview"><b>已知量整理：</b>${esc(ans.known)}</div>`:''}<ol>${listHtml(ans.steps)}</ol>${ans.conclusion?`<div class="answer-conclusion"><b>结论：</b>${esc(ans.conclusion)}</div>`:''}</div>`; }
function renderExtra(r){
 const diagram = r.diagram ? `<div class="diagram-note"><b>图示建议：</b>${esc(r.diagram)}</div>` : '';
 const usage = r.usage ? `<div class="resource-extra"><b>教学使用：</b><br>${esc(r.usage)}</div>` : '';
 const difficulty = r.difficulty ? `<div class="resource-extra"><b>适合学生：</b><br>${esc(r.difficulty)}</div>` : '';
 const quality = (r.qualityCheck||[]).length ? `<div class="resource-extra" style="grid-column:1/-1"><b>质量核查：</b><div class="quality-list">${(r.qualityCheck||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>` : '';
 return `${diagram}${(usage||difficulty||quality)?`<div class="resource-extra-grid">${usage}${difficulty}${quality}</div>`:''}`;
}
window.resourceCard=function(r){
 const id=r.id||('res_'+Math.random().toString(36).slice(2));
 const source=(r.sourceChain||[]).map((s,i)=>`<div class="source-item"><div class="source-code">${esc(s.code||('来源'+(i+1)))}</div><div class="source-text">${esc(s.text||s)}</div></div>${i<(r.sourceChain||[]).length-1?'<div class="source-arrow">↓</div>':''}`).join('');
 const compare=(r.compare||[]).length?`<table class="compare-table"><thead><tr><th>维度</th><th>整合/变式前</th><th>成品题中体现</th></tr></thead><tbody>${(r.compare||[]).map(row=>`<tr><td>${esc(row[0])}</td><td>${esc(row[1])}</td><td>${esc(row[2])}</td></tr>`).join('')}</tbody></table>`:'';
 const coding=(r.coding||[]).length?`<div class="coding-flow">${(r.coding||[]).map(x=>`<span class="coding-pill ${x.changed?'changed':''}">${esc(x.text)}</span>${x.arrow?'<span class="coding-arrow">→</span>':''}`).join('')}</div>`:'';
 const chain=(r.chain||[]).length?`<div class="mini-section-title">变式链 / 训练梯度</div><div class="chain-row">${(r.chain||[]).map(x=>`<div class="chain-card"><b>${esc(x.title)}</b><span>${esc(x.desc)}</span></div>`).join('')}</div>`:'';
 const labels=(r.labels||[]).length?`<div class="scenario-labels">${r.labels.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:'';
 const student=`<div class="resource-view student-view active" data-view="student"><h5>${esc(r.title)}</h5><p><b>题干：</b>${esc(r.stem)}</p><p><b>设问：</b></p><ol>${listHtml(r.questions)}</ol></div>`;
 const teacher=`<div class="resource-view teacher-view" data-view="teacher"><h5>${esc(r.title)}｜教师备课版</h5><div class="mini-section-title">来源链</div><div class="source-chain">${source||'<div class="source-item"><div class="source-code">母题</div><div class="source-text">保留原题核心物理模型，按教学目标进行加工。</div></div>'}</div><div class="mini-section-title">整合/变式前后对比</div>${compare}${coding}<div class="mini-section-title">题干与设问</div><p><b>题干：</b>${esc(r.stem)}</p><ol>${listHtml(r.questions)}</ol>${renderStdAnswer(r.standardAnswer)}<div class="mini-section-title">参考思路与教学提示</div><div class="teacher-note-grid"><div class="teacher-note"><b>解题路径</b><br>${esc(r.solutionPath||'先提取信息，再建立模型，最后完成计算或判断。')}</div><div class="teacher-note"><b>关键公式</b><br>${esc(r.formulas||'依据具体模型选择运动学公式、平衡条件或牛顿第二定律。')}</div><div class="teacher-note"><b>易错点</b><br>${esc(r.misconception||'注意单位、方向、模型适用条件与题目设问边界。')}</div><div class="teacher-note"><b>追问建议</b><br>${esc(r.followUp||'改变一个条件，让学生判断模型或结论是否发生变化。')}</div></div>${renderExtra(r)}${chain}${labels}</div>`;
 const screen=`<div class="resource-view screen-view" data-view="screen"><h5>${esc(r.title)}</h5><p>${esc(r.stem)}</p><ol>${listHtml((r.questions||[]).slice(0,4))}</ol></div>`;
 return `<div class="resource-pack" id="${id}"><div class="resource-head"><div><div class="eyebrow">${esc(r.type||'成品题资源包')}</div><h4>${esc(r.title)}</h4><div class="resource-sub">${esc(r.summary||'已整理为可直接用于课堂的题目成品，包含学生版、教师版与投屏版。')}</div><div class="resource-tags">${tagsHtml(r.tags)}</div></div><div class="copy-row"><button class="copy-btn" onclick="copyResource('${id}','student')">复制学生版</button><button class="copy-btn" onclick="copyResource('${id}','teacher')">复制教师版</button><button class="copy-btn" onclick="copyResource('${id}','screen')">复制投屏版</button></div></div><div class="resource-tabs"><button class="active" data-tab="student" onclick="showResourceView('${id}','student')">学生练习版</button><button data-tab="teacher" onclick="showResourceView('${id}','teacher')">教师备课版</button><button data-tab="screen" onclick="showResourceView('${id}','screen')">课堂投屏版</button></div>${student}${teacher}${screen}</div>`;
};
function commonTags(){return {type:'整合成品题',tags:[{text:'含标准答案',kind:'green'},{text:'含来源链'},{text:'可复制',kind:'warm'}]};}
window.productForCase=function(cid){const common=commonTags();const cases={
 'friction-rj':{...common,id:'case_product_friction_v14',title:'救援物资箱的拖拽与摩擦力判断',summary:'以 RJ-04 为主干，借鉴 LK-05 的策略提炼，补入 HK-06 的临界摩擦判断；配完整计算答案。',stem:'救援队员需要把一只质量为 20 kg 的物资箱沿水平地面拖到指定位置。物资箱与地面间的动摩擦因数为 0.30，最大静摩擦力为 80 N，取 g=10 N/kg。队员用水平绳缓慢增大拉力。',questions:['当拉力为 40 N 时，物资箱是否运动？此时摩擦力多大？','当拉力增大到 80 N 时，物资箱处于怎样的临界状态？摩擦力多大？','当拉力继续增大到 120 N 后，物资箱开始运动。此时滑动摩擦力多大？若拉力保持 120 N，物资箱的加速度多大？','方法总结：解决摩擦力问题为什么要先判断“动摩擦还是静摩擦”？'],sourceChain:[{code:'RJ-04',text:'提供“雪橇匀速运动求拉力”的基础模型，作为层级Ⅰ入口。'},{code:'LK-05',text:'提供策略提炼与迁移追问，强化“抓主要因素、先判动静”的方法支架。'},{code:'HK-06',text:'提供动静摩擦临界判断，推动题目由直接计算转向分析建模。'}],compare:[['情境','马拉雪橇生活情境','救援物资箱拖拽，保留生活经验并强化任务真实性'],['设问','单步求拉力','加入静摩擦、临界状态、滑动摩擦与加速度'],['助学','无栏目','加入策略提炼与迁移追问'],['层级','层级Ⅰ','层级Ⅰ→层级Ⅱ']],coding:[{text:'D1 生活情境',arrow:true},{text:'生活任务强化',changed:true},{text:'D5 无栏目',arrow:true},{text:'方法策略类',changed:true},{text:'D6 Ⅰ',arrow:true},{text:'Ⅰ→Ⅱ',changed:true}],standardAnswer:{overview:'本题的关键是先判断物资箱是否已经运动。未运动时是静摩擦力，摩擦力会随外力自调节；运动后才使用滑动摩擦力公式。',known:'m=20 kg，μ=0.30，fmax=80 N，g=10 N/kg，N=mg=200 N。',steps:['拉力 F=40 N，小于最大静摩擦力 80 N，物资箱保持静止；为平衡拉力，静摩擦力大小 f=40 N，方向与拉力相反。','拉力 F=80 N，达到最大静摩擦力，物资箱处于将要运动的临界状态；此时摩擦力大小为 80 N。','物资箱运动后，滑动摩擦力 f=μN=0.30×200=60 N。','当拉力 F=120 N 时，水平方向合力 F合=120-60=60 N，由 F合=ma 得 a=60/20=3.0 m/s²。'],conclusion:'摩擦力问题必须先判动静。三种情况下摩擦力分别为 40 N、80 N、60 N；第三种情况下加速度为 3.0 m/s²。'},solutionPath:'先判动静 → 求正压力 → 选择静摩擦或滑动摩擦规则 → 必要时用牛顿第二定律求加速度。',formulas:'f静≤fmax；f滑=μN；F合=ma。',misconception:'不要一看到摩擦因数就直接套 f=μN；静摩擦力不一定等于 μN。',followUp:'如果绳子改成斜向上拉，正压力如何变化？滑动摩擦力又如何变化？',diagram:'画出物资箱、水平拉力 F、重力 G、支持力 N、摩擦力 f；在第 3 问中用合力箭头突出 F-f。',usage:'适合摩擦力新授后的进阶练习，建议 10 分钟完成：前两问独立作答，第 3 问板演，第 4 问全班归纳。',difficulty:'基础中等学生可完成前 3 问；基础较强学生可继续讨论斜向拉力或传送带变式。',qualityCheck:['数据合理','单位统一','动静摩擦边界清楚','层级递进明确','可直接课堂使用'],labels:['新授例题','基础训练','层级提升']},
 'balance-rj':{...common,id:'case_product_balance_v14',title:'风力仪读数与共点力平衡',summary:'保留人教版规范表达，借鉴鲁科版策略提炼与沪科版反思追问；补完整答案与三层图示。',stem:'某简易风力仪由细线和小球组成。小球质量为 0.20 kg，静止时细线竖直；有水平风吹来时，小球偏离竖直方向，细线与竖直方向成 30°角并保持静止。取 g=10 N/kg。',questions:['以小球为研究对象，画出受力示意图。','求风对小球的水平作用力大小。','若风力增大，偏角如何变化？请结合平衡条件说明。','比较“正交分解法”和“力三角形法”，哪一种更适合本题？为什么？'],sourceChain:[{code:'RJ-06/RJ-07',text:'提供共点力平衡的规范三段式表达与受力分析主干。'},{code:'LK-08',text:'提供“选择研究对象→受力分析→坐标分解→列方程”的策略提炼。'},{code:'HK-09/HK-10',text:'提供方法比较、坐标轴选择等反思评价追问。'}],compare:[['图示','单一示意图','情境图→受力图→几何关系图'],['结构','标准三段式','案例闭环式'],['助学','无或较少','方法策略+反思评价'],['层级','层级Ⅱ','层级Ⅱ并向方法评价延伸']],coding:[{text:'D3 示意/复合',arrow:true},{text:'三层图示',changed:true},{text:'D4 三段式',arrow:true},{text:'案例闭环',changed:true},{text:'D5 无',arrow:true},{text:'策略+反思',changed:true}],standardAnswer:{overview:'小球静止，受到重力、细线拉力和水平风力三个共点力，合力为零。',known:'m=0.20 kg，g=10 N/kg，θ=30°，mg=2.0 N。',steps:['画受力图：重力 mg 竖直向下，拉力 T 沿细线方向，风力 F 水平。','沿竖直方向：Tcosθ=mg；沿水平方向：Tsinθ=F。','两式相除得 F/mg=tanθ，所以 F=mg·tanθ。','代入 θ=30°：F=2.0×tan30°≈2.0×0.577≈1.15 N。','若偏角增大，tanθ 增大，因此风力增大；当 θ=45° 时，F=2.0 N。'],conclusion:'风对小球的水平作用力约为 1.15 N。正交分解法步骤稳定，力三角形法更简洁但对几何关系要求更高。'},solutionPath:'选择小球为研究对象 → 画三力平衡图 → 正交分解 → 消去拉力 T → 得到 F=mg·tanθ。',formulas:'ΣFx=0，ΣFy=0，F=mg·tanθ。',misconception:'偏角是与竖直方向的夹角，不能把 tanθ 写反；风力是水平力，不是沿细线方向的力。',followUp:'若小球质量加倍而偏角仍为 30°，风力读数如何变化？',diagram:'第一层画风力仪情境图；第二层只保留小球并画三力；第三层画直角三角形关系，标出 θ、mg、F。',usage:'适合共点力平衡方法提升课或复习课，建议先让学生画图，再由图推式。',difficulty:'适合已经掌握力的分解和平衡条件的学生。',qualityCheck:['受力对象明确','几何角度明确','公式推导完整','方法比较可展开'],labels:['共点力平衡','方法比较','课堂投屏']},
 'newton-lk':{...common,id:'case_product_newton_v14',title:'从高铁启动到航天发射的牛顿第二定律应用题组',summary:'以鲁科版主干为基础，补工程、探究与 STSE；把符号题补成含数据的可讲题组。',stem:'围绕“力与运动变化的关系”设计四个任务。任务 A：一列高铁质量为 2.0×10⁵ kg，启动时牵引力为 1.6×10⁵ N，阻力为 4.0×10⁴ N。任务 B：某火箭发射初期总质量为 3.0×10⁵ kg，发动机推力为 4.5×10⁶ N，取 g=10 N/kg，忽略空气阻力。任务 C：检验公式 a=F/m 是否量纲合理。任务 D：结合交通制动数据判断校门口车辆是否超速。',questions:['任务 A 中高铁启动阶段的加速度是多少？','任务 B 中火箭发射初期的加速度是多少？','用量纲分析判断 a=F/m 是否合理。','说明为什么同一条牛顿第二定律可以服务于工程计算、科学方法和交通安全裁决。'],sourceChain:[{code:'LK-09~LK-12',text:'提供鲁科版原有层级Ⅰ/Ⅱ主干与策略迁移风格。'},{code:'JK-17',text:'补入航天工程情境。'},{code:'JK-18',text:'补入科学探究与量纲分析。'},{code:'YJ-16',text:'补入 STSE 法规裁决任务。'}],compare:[['情境覆盖','生活+纯模型','生活+工程+科学探究+STSE'],['认知梯度','Ⅰ/Ⅱ为主','Ⅰ→Ⅱ→Ⅲ'],['素养指向','物理观念、科学思维','进一步覆盖科学探究、科学态度与责任']],coding:[{text:'D1 生活/模型',arrow:true},{text:'多情境覆盖',changed:true},{text:'D6 Ⅰ/Ⅱ',arrow:true},{text:'Ⅰ→Ⅱ→Ⅲ',changed:true}],standardAnswer:{overview:'四个任务共同围绕 F合=ma 展开，但功能不同：计算、工程解释、方法检验和社会裁决。',known:'任务 A：m=2.0×10⁵ kg，F=1.6×10⁵ N，f=4.0×10⁴ N。任务 B：M=3.0×10⁵ kg，T=4.5×10⁶ N，Mg=3.0×10⁶ N。',steps:['任务 A：合力 F合=F-f=1.2×10⁵ N，a=F合/m=1.2×10⁵/(2.0×10⁵)=0.60 m/s²。','任务 B：合力 F合=T-Mg=4.5×10⁶-3.0×10⁶=1.5×10⁶ N，a=F合/M=1.5×10⁶/(3.0×10⁵)=5.0 m/s²。','量纲检验：F 的单位 N=kg·m/s²，F/m 的单位为 m/s²，与加速度量纲一致，所以 a=F/m 在量纲上合理。','交通裁决任务中，先由运动或受力求加速度/初速度，再与限速标准比较，体现物理计算服务社会判断。'],conclusion:'本题组从直接应用走向工程解释和方法评价，形成牛顿第二定律的大章综合训练。'},solutionPath:'统一从 F合=ma 出发，区分已知力求加速度、量纲检验和外部标准裁决三类任务。',formulas:'F合=ma；N=kg·m/s²；a 的量纲为 m/s²。',misconception:'火箭受到的合力不是发动机推力 T，而是 T-Mg；量纲合理不代表公式一定物理正确。',followUp:'若空气阻力不可忽略，火箭加速度会如何变化？',diagram:'画高铁受力示意图、火箭竖直方向受力图，并用一个小流程图表示“受力→加速度→运动判断”。',usage:'适合牛顿运动定律章末复习或专题整合，建议分小组完成四个任务。',difficulty:'适合中上水平班级；基础薄弱班级可只完成任务 A、B。',qualityCheck:['数据数量级合理','合力方向清楚','科学探究与工程情境可区分','层级梯度完整'],labels:['大章整合','专题复习','素养覆盖']},
 'traffic-rj':{...common,id:'case_product_traffic_v14',title:'校门口交通制动安全综合分析',summary:'借鉴交通制动安全模型的多版本资源，补完整计算过程、安全判断和法规裁决。',stem:'一辆汽车以 54 km/h 的速度驶近学校门口，司机发现前方 40 m 处有行人横穿道路。司机反应时间为 0.8 s，踩下刹车后汽车做匀减速直线运动，加速度大小为 6.0 m/s²。学校门口限速为 40 km/h。',questions:['将 54 km/h 化为 m/s，并求司机反应时间内汽车前进的距离。','汽车从开始刹车到停止需要多长时间？制动距离是多少？','该车能否在撞到行人前安全停下？请用“总距离 = 反应距离 + 制动距离”判断。','该车进入校门口前是否超速？请说明你的法规裁决依据。','若雨天路面湿滑导致加速度大小减小为 4.0 m/s²，原来的安全判断是否改变？'],sourceChain:[{code:'HKJ-03',text:'提供基础加速度计算入口。'},{code:'RJ-01/RJ-03',text:'提供两阶段运动衔接与逆向分析主干。'},{code:'LK-02',text:'提供“先判断停止时间”的刹车陷阱。'},{code:'YJ-05/HK-04',text:'提供安全距离裁决。'},{code:'YJ-16/HKJ-07',text:'提供限速法规裁决。'}],compare:[['任务性质','计算位移、速度或加速度','计算→比较→安全/法规裁决'],['过程结构','单段或两段运动','反应段+制动段+雨天变式'],['层级','层级Ⅱ主干','层级Ⅰ入口→Ⅱ建模→Ⅲ裁决']],coding:[{text:'D6 Ⅱ',arrow:true},{text:'Ⅰ→Ⅱ→Ⅲ',changed:true},{text:'D5 无/少',arrow:true},{text:'反思评价',changed:true},{text:'D1 生活',arrow:true},{text:'STSE',changed:true}],standardAnswer:{overview:'本题分为反应阶段和制动阶段。安全判断要用总距离，不能只看制动距离。',known:'v0=54 km/h=15 m/s；t反=0.8 s；a=6.0 m/s²；障碍距离 40 m；限速 40 km/h≈11.1 m/s。',steps:['速度换算：54 km/h=54÷3.6=15 m/s。反应距离 s1=v0t反=15×0.8=12 m。','制动时间：0=v0-at，所以 t=v0/a=15/6.0=2.5 s。','制动距离：s2=v0²/(2a)=15²/(2×6.0)=225/12=18.75 m。','总停车距离：s=s1+s2=12+18.75=30.75 m。因为 30.75 m<40 m，理论上能在行人前停下，安全余量为 9.25 m。','超速判断：54 km/h>40 km/h，因此进入校门口前已经超速。','雨天 a=4.0 m/s² 时，s2=15²/(2×4.0)=28.125 m，总距离 s=12+28.125=40.125 m，大于 40 m，不能安全停下。'],conclusion:'普通路面理论上能停下但车辆已超速；雨天路面不能安全停下。物理计算支持了安全与法规两类裁决。'},solutionPath:'统一单位 → 分反应段与制动段 → 计算总停车距离 → 与障碍距离比较 → 与限速标准比较。',formulas:'s反=v0t反；v=v0-at；s制=v0²/(2a)；s总=s反+s制。',misconception:'只计算制动距离会低估危险；km/h 必须先换算成 m/s；“能停下”和“未超速”是两个不同判断。',followUp:'如果司机反应时间增加到 1.2 s，安全判断如何变化？',diagram:'画一条道路线段：汽车起点、反应距离 12 m、制动距离 18.75 m、行人位置 40 m；雨天变式用另一条制动距离箭头对比。',usage:'适合匀变速直线运动复习课或 STSE 拓展课，建议 12–15 分钟。',difficulty:'适合中等及以上学生；基础薄弱班级可删去雨天变式和法规裁决。',qualityCheck:['单位换算明确','两阶段过程清楚','安全标准可比较','层级Ⅰ→Ⅱ→Ⅲ完整','数据结论不矛盾'],labels:['交通安全','STSE','层级Ⅲ','专题复习']}
}; return cases[cid]||cases['traffic-rj'];};
window.integratedProduct=function(c,all){return resourceCard(productForCase(c.id));};
function answerForBase(base){
 if(base==='traffic') return {standardAnswer:{overview:'按交通制动模型处理：反应阶段匀速，制动阶段匀减速，最后与外部标准比较。',known:'常用示例数据：v0=54 km/h=15 m/s，t反=0.8 s，a=6.0 m/s²，障碍距离 40 m，限速 40 km/h。',steps:['反应距离 s1=15×0.8=12 m。','制动距离 s2=15²/(2×6.0)=18.75 m。','总停车距离 s=30.75 m，小于 40 m，普通路面可停下。','若雨天 a=4.0 m/s²，s2=28.125 m，总距离 40.125 m，不能安全停下。','54 km/h 大于 40 km/h，因此存在超速行为。'],conclusion:'交通制动变式应同时关注计算结果和安全/法规裁决。'},diagram:'建议画反应距离、制动距离和障碍位置的线段图，若涉及雨天可画两条制动距离对比箭头。'};
 if(base==='friction') return {standardAnswer:{overview:'先判动静摩擦，再决定公式。',known:'m=20 kg，μ=0.30，fmax=80 N，g=10 N/kg，N=200 N。',steps:['F=40 N<fmax，物体静止，f=40 N。','F=80 N=fmax，临界将动，f=80 N。','运动后 f滑=μN=60 N；若 F=120 N，则 F合=60 N，a=3.0 m/s²。'],conclusion:'三种状态分别对应静止、临界和滑动，摩擦力计算规则不同。'},diagram:'建议画物块受力图，分别标出 F、f、N、G；临界状态用虚线标注“将要运动”。'};
 if(base==='balance') return {standardAnswer:{overview:'按共点力平衡处理，三力合力为零。',known:'常用示例：m=0.20 kg，g=10 N/kg，θ=30°，mg=2.0 N。',steps:['受力：重力 mg、细线拉力 T、水平风力 F。','平衡方程：Tcosθ=mg，Tsinθ=F。','消去 T 得 F=mg·tanθ。','代入 θ=30°，F≈2.0×0.577=1.15 N。'],conclusion:'风力大小约为 1.15 N；若 θ 增大，风力增大。'},diagram:'建议使用三层图：情境图、受力图、几何关系图。'};
 if(base==='fall') return {standardAnswer:{overview:'近似自由落体时，由 h=1/2gt² 和 v=gt 求解。',known:'示例：h=20 m，g=10 m/s²。',steps:['由 h=1/2gt² 得 t=sqrt(2h/g)=sqrt(40/10)=2.0 s。','落地前速度 v=gt=20 m/s。','若学生离开危险区需要 1.5 s，理想条件下有 0.5 s 余量，但实际仍需考虑反应延迟与空气阻力。'],conclusion:'自由落体题的拓展可从计算走向安全判断或模型修正。'},diagram:'建议画竖直高度、下落路径和时间标注。'};
 return {standardAnswer:{overview:'依据母题核心模型完成求解，并补充判断或迁移。',steps:['提取研究对象和已知量。','建立对应物理模型。','选择公式或方程。','完成计算并检查结论是否符合情境。'],conclusion:'该变式可作为教师进一步人工精修的题目骨架。'},diagram:'建议按“情境图→模型图→关键关系图”的顺序设计图示。'};
}
window.generateVariation=function(){const p=byCode[qs('#varProblem').value]||PROBLEMS[0];const e=extractElements(p);const out=variationByType(p,e,currentVariationType);const base=vBase(p,e);const typeMap={D1:'情境变式',D2:'知识联结变式',D3:'图示重构变式',D4:'结构升级变式',D5:'助学支架变式',D6:'层级提升变式'};const extra=answerForBase(base);const res={id:'variation_pack_v14_'+p.code.replace(/[^a-zA-Z0-9]/g,'_'),type:'变式成品题',title:`${p.code}《${p.title}》｜${out.name}`,summary:`${out.note}。已补充标准解答、图示建议与质量核查。`,stem:out.stem,questions:out.questions,sourceChain:[{code:p.code,text:'提供母题情境、核心模型与原始设问。'},{code:typeMap[currentVariationType]||currentVariationType,text:'根据母题题干要素进行定向改造，并补充可讲解的答案链。'}],compare:[['母题核心',`${p.title}｜${e.核心模型}`,'保留核心模型，重新组织题干与设问'],['改造方向',`${p.situation||p.d1} / ${p.level||p.d6}`,out.note],['课堂形态','教材原题','练习版、教师版、投屏版三用']],coding:[{text:`原：${p.situation||p.d1}`,arrow:true},{text:`变式后：${out.code.split('/')[0].trim()}`,changed:true},{text:`原：${p.level||p.d6}`,arrow:true},{text:(out.code.match(/层级[ⅠⅡⅢ][^/，]*/)||['层级变化'])[0],changed:true}],standardAnswer:extra.standardAnswer,diagram:extra.diagram,solutionPath:out.teach,formulas:base==='traffic'?'s反=v0t；s制=v0²/(2a)；F合=ma 可联结':base==='friction'?'f静≤fmax；f滑=μN；F合=ma':base==='balance'?'Tcosθ=mg；Tsinθ=F；F=mg·tanθ':base==='fall'?'h=1/2gt²；v=gt':'依据母题核心模型选择公式',misconception:base==='traffic'?'忽略反应时间或单位换算会导致安全判断错误。':base==='friction'?'静摩擦力和滑动摩擦力的计算规则不同。':base==='balance'?'受力图和几何关系图不能混淆，tanθ 关系容易写反。':'注意模型适用条件。',followUp:'继续改变一个条件，要求学生判断模型、路径或结论是否变化。',usage:'可作为课堂练习、课后作业或专题复习中的一环。',difficulty:base==='traffic'||base==='balance'?'适合中等及以上学生，基础班可保留前两问。':'适合基础到中等学生，教师可按学情删减高阶问。',qualityCheck:['题干数据完整','设问层次清楚','答案链可追踪','编码变化明确'],chain:chainForBase(base),labels:['变式链','含答案','教师备课'],tags:[{text:typeMap[currentVariationType]||'六维变式',kind:'warm'},{text:'含解答',kind:'green'},{text:'可复制'}]};qs('#variationOutput').innerHTML=`<div class="output"><div class="eyebrow">${esc(typeMap[currentVariationType]||currentVariationType)} · 答案解析增强</div><h3>${esc(p.code)}《${esc(p.title)}》的变式结果</h3><div class="output-section"><b>① 母题要素</b>${renderElements(p)}</div><div class="output-section"><b>② 变式题成品与解答</b>${resourceCard(res)}</div></div>`;};
window.renderCaseOutput=function(){const c=(DATA.integrationCases||[]).find(x=>x.id===currentCaseId);if(!c){qs('#caseOutput').innerHTML='';return}const steps=c.steps||[];const codes=c.codes||[];const all=codes.map(x=>byCode[x]).filter(Boolean);const first=all[0];qs('#caseOutput').innerHTML=`<div class="output integrated-product"><div class="eyebrow">${esc(c.path)} · v14 答案解析增强</div><h3>${esc(c.title)}</h3><p class="meta">${esc(c.summary)}</p><div class="output-section"><b>① 主用题与借鉴题要素</b>${first?renderElements(first):''}<div class="details"><div class="flow">${steps.map(s=>`<div class="flow-item"><div><b>${esc(s.op)}</b><br><span class="tiny">${esc((s.codes||[]).join(' + '))}</span></div><div>${esc(s.text)}<br><span class="tag gray">${esc(roleOfStep(s))}</span></div></div>`).join('')}</div></div></div><div class="output-section"><b>② 整合后的成品题资源包（含标准解答）</b>${resourceCard(productForCase(c.id))}</div><div class="output-section"><b>③ 四项原则复核</b><br>互补性：每一道题承担明确功能，不做同类重复。<br>课标一致性：至少覆盖物理观念与科学思维；涉及安全、工程或探究时进一步指向科学态度与责任、科学探究。<br>认知梯度：按“入口题—主干题—提升题”组织，避免直接跳到高阶。<br>学情适切性：基础弱班保留前两问或前两题，基础强班完整展开高阶判断。</div></div>`;};
// 重新渲染当前页面中的结果
setTimeout(function(){try{ if(typeof renderCaseOutput==='function') renderCaseOutput(); if(typeof generateVariation==='function') generateVariation(); }catch(e){console.warn('v14 refresh',e)}},100);
})();
